### ISSUE TITLE
lost files

### ISSUE THREAD

**Issue by hzlhzlhzlhzl** [air029/PolyFormer#1]
No such file or directory: './bases/questions_cheb_10.pkl'
No such file or directory: './bases/physics_mono_4.pkl'
No such file or directory: './bases/physics_cheb_2.pkl'
No such file or directory: './bases/questions_mono_12.pkl'

**Comment by air029** [comment]
Hi,
Apologies for the inconvenience. To resolve this issue, please create a directory named `./bases` before running the script. You can do this by executing the following command:
`mkdir ./bases`
After that, you can proceed with running:
`sh node_classification.sh`
This will generate files like `questions_cheb_10.pkl`, `physics_mono_4`, and others in the `./bases` directory.
Best regards
